# Generated by Django 5.1.7 on 2025-04-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=250)),
                ('contact', models.IntegerField()),
                ('project', models.CharField(max_length=70)),
                ('billing_status', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=250)),
                ('contact', models.IntegerField()),
                ('department', models.CharField(max_length=70)),
                ('emp_id', models.IntegerField()),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=250)),
                ('contact', models.IntegerField()),
                ('course', models.CharField(max_length=70)),
                ('roll_no', models.IntegerField()),
            ],
        ),
    ]
